### ISSUE TITLE
use the right variables in Makefiles

### ISSUE THREAD

**Issue by sanchez-lucas** [CustomEntity/Project-With-Multiple-Makefile-Template#1]
As you may know, Makefiles come along with prebuilt features wich could be used instead of doing your own handmade features.

Some examples :
- `CFLAGS` Extra flags to give to the C compiler such as `-W -Wall -Wextra -Werror`
- `LDFLAGS` : Extra flags to give to compilers when they are supposed to invoke the linker, `ld`, such as `-L`. Libraries (`-lfoo`) should be added to the LDLIBS variable instead
- `LDLIBS` : Library flags or names given to compilers when they are supposed to invoke the linker, `ld`. Non-library linker flags, such as `-L`, should go in the LDFLAGS variable
- `CPPFLAGS` : Extra flags to give to the C preprocessor and programs that use it such as `-I ./include`
- `CC` : Program for compiling C programs; default `cc`
- `RM` : Command to remove a file; default `rm -f`

**Comment by CustomEntity** [comment]
Hello ! Thank you very much for your interest in this project ! I have indeed forgotten a lot of prebuilt features, I will fix that as soon as possible.

**Comment by CustomEntity** [comment]
It should be better now :)
